client_ip_restore_enabled: false
bypass_host: edit.covid19.sl
valid_credentials: true
zone_id: 2ad2213f85dc55c34c99b82056ffbe83
apikey: 684449e4705af48495e17ea82d7116d6908fb
email: tamba@tambalamin.me
_core:
  default_config_hash: nmZKXyrMlwu9Q3wkp-OLApl-rO94n1bVxWlDYBF7Tqw
