flippy_chc_manufacturer: 0
flippy_head_chc_manufacturer: 0
flippy_show_empty_chc_manufacturer: 0
flippy_prev_label_chc_manufacturer: ''
flippy_next_label_chc_manufacturer: ''
flippy_first_last_chc_manufacturer: 0
flippy_first_label_chc_manufacturer: ''
flippy_last_label_chc_manufacturer: ''
flippy_loop_chc_manufacturer: 0
flippy_random_chc_manufacturer: 0
flippy_random_label_chc_manufacturer: ''
flippy_truncate_chc_manufacturer: ''
flippy_ellipse_chc_manufacturer: ''
flippy_press_swipe_chc_manufacturer: null
flippy_custom_sorting_chc_manufacturer: 0
flippy_sort_chc_manufacturer: nid
flippy_order_chc_manufacturer: ASC
flippy_chc_vendor: 0
flippy_head_chc_vendor: 0
flippy_show_empty_chc_vendor: 0
flippy_prev_label_chc_vendor: ''
flippy_next_label_chc_vendor: ''
flippy_first_last_chc_vendor: 0
flippy_first_label_chc_vendor: ''
flippy_last_label_chc_vendor: ''
flippy_loop_chc_vendor: 0
flippy_random_chc_vendor: 0
flippy_random_label_chc_vendor: ''
flippy_truncate_chc_vendor: ''
flippy_ellipse_chc_vendor: ''
flippy_press_swipe_chc_vendor: null
flippy_custom_sorting_chc_vendor: 0
flippy_sort_chc_vendor: nid
flippy_order_chc_vendor: ASC
flippy_chs_products: 0
flippy_head_chs_products: 0
flippy_show_empty_chs_products: 0
flippy_prev_label_chs_products: ''
flippy_next_label_chs_products: ''
flippy_first_last_chs_products: 0
flippy_first_label_chs_products: ''
flippy_last_label_chs_products: ''
flippy_loop_chs_products: 0
flippy_random_chs_products: 0
flippy_random_label_chs_products: ''
flippy_truncate_chs_products: ''
flippy_ellipse_chs_products: ''
flippy_press_swipe_chs_products: null
flippy_custom_sorting_chs_products: 0
flippy_sort_chs_products: nid
flippy_order_chs_products: ASC
flippy_chs_canvas_page: 0
flippy_head_chs_canvas_page: 0
flippy_show_empty_chs_canvas_page: 0
flippy_prev_label_chs_canvas_page: ''
flippy_next_label_chs_canvas_page: ''
flippy_first_last_chs_canvas_page: 0
flippy_first_label_chs_canvas_page: ''
flippy_last_label_chs_canvas_page: ''
flippy_loop_chs_canvas_page: 0
flippy_random_chs_canvas_page: 0
flippy_random_label_chs_canvas_page: ''
flippy_truncate_chs_canvas_page: ''
flippy_ellipse_chs_canvas_page: ''
flippy_press_swipe_chs_canvas_page: null
flippy_custom_sorting_chs_canvas_page: 0
flippy_sort_chs_canvas_page: nid
flippy_order_chs_canvas_page: ASC
flippy_chs_press: 0
flippy_head_chs_press: 0
flippy_show_empty_chs_press: 0
flippy_prev_label_chs_press: ''
flippy_next_label_chs_press: ''
flippy_first_last_chs_press: 0
flippy_first_label_chs_press: ''
flippy_last_label_chs_press: ''
flippy_loop_chs_press: 0
flippy_random_chs_press: 0
flippy_random_label_chs_press: ''
flippy_truncate_chs_press: ''
flippy_ellipse_chs_press: ''
flippy_press_swipe_chs_press: null
flippy_custom_sorting_chs_press: 0
flippy_sort_chs_press: nid
flippy_order_chs_press: ASC
flippy_chs_covid_19_case: 0
flippy_head_chs_covid_19_case: 0
flippy_show_empty_chs_covid_19_case: 0
flippy_prev_label_chs_covid_19_case: ''
flippy_next_label_chs_covid_19_case: ''
flippy_first_last_chs_covid_19_case: 0
flippy_first_label_chs_covid_19_case: ''
flippy_last_label_chs_covid_19_case: ''
flippy_loop_chs_covid_19_case: 0
flippy_random_chs_covid_19_case: 0
flippy_random_label_chs_covid_19_case: ''
flippy_truncate_chs_covid_19_case: ''
flippy_ellipse_chs_covid_19_case: ''
flippy_press_swipe_chs_covid_19_case: null
flippy_custom_sorting_chs_covid_19_case: 0
flippy_sort_chs_covid_19_case: nid
flippy_order_chs_covid_19_case: ASC
